/* ============================================================
   MapMaster | data.js
   All static data: MAPS, FLAGS, CAPITALS, MAP_SUPPORT, INDIA_UTS
   ============================================================ */

const MAPS = {
  india: {
    name:    "India",
    svg:     "svg/india.svg",
    regions: [
      "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar",
      "Chhattisgarh", "Goa", "Gujarat", "Haryana",
      "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala",
      "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya",
      "Mizoram", "Nagaland", "Odisha", "Punjab",
      "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
      "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
    ]
  },
  usa: {
    name:    "USA",
    svg:     "svg/usa.svg",
    regions: [
      "Alabama", "Alaska", "Arizona", "Arkansas",
      "California", "Colorado", "Connecticut", "Delaware",
      "Florida", "Georgia", "Hawaii", "Idaho",
      "Illinois", "Indiana", "Iowa", "Kansas",
      "Kentucky", "Louisiana", "Maine", "Maryland",
      "Massachusetts", "Michigan", "Minnesota", "Mississippi",
      "Missouri", "Montana", "Nebraska", "Nevada",
      "New Hampshire", "New Jersey", "New Mexico", "New York",
      "North Carolina", "North Dakota", "Ohio", "Oklahoma",
      "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
      "South Dakota", "Tennessee", "Texas", "Utah",
      "Vermont", "Virginia", "Washington", "West Virginia",
      "Wisconsin", "Wyoming"
    ]
  },
  canada: {
    name: "Canada",
    svg:  "svg/canada.svg",
    regions: [
      "Alberta", "British Columbia", "Manitoba", "New Brunswick",
      "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia",
      "Nunavut", "Ontario", "Prince Edward Island",
      "Quebec", "Saskatchewan", "Yukon"
    ]
  },
  australia: {
    name: "Australia",
    svg:  "svg/australia.svg",
    regions: [
      "Australian Capital Territory", "New South Wales", "Northern Territory",
      "Queensland", "South Australia", "Tasmania",
      "Victoria", "Western Australia"
    ]
  },
  japan: {
    name: "Japan",
    svg:  "svg/japan.svg",
    regions: [
      "Aichi", "Akita", "Aomori", "Chiba", "Ehime",
      "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gunma",
      "Hiroshima", "Hokkaido", "Hyogo", "Ibaraki", "Ishikawa",
      "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
      "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki",
      "Nagano", "Nagasaki", "Nara", "Niigata", "Oita",
      "Okayama", "Okinawa", "Osaka", "Saga", "Saitama",
      "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima",
      "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata",
      "Yamaguchi", "Yamanashi"
    ]
  },
  germany: {
    name: "Germany",
    svg:  "svg/germany.svg",
    regions: [
      "Baden-Wurttemberg", "Bavaria", "Berlin", "Brandenburg",
      "Bremen", "Hamburg", "Hesse", "Lower Saxony",
      "Mecklenburg-Vorpommern", "North Rhine-Westphalia",
      "Rhineland-Palatinate", "Saarland", "Saxony",
      "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"
    ]
  },
  china: {
    name: "China",
    svg:  "svg/china.svg",
    regions: [
      "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu",
      "Guangdong", "Guangxi Zhuang", "Guizhou", "Hainan", "Hebei",
      "Heilongjiang", "Henan", "Hong Kong", "Hubei", "Hunan",
      "Jiangsu", "Jiangxi", "Jilin", "Liaoning", "Macau",
      "Nei Mongol", "Ningxia Hui", "Qinghai", "Shaanxi", "Shandong",
      "Shanghai", "Shanxi", "Sichuan", "Tianjin", "Xinjiang Uygur",
      "Xizang (Tibet)", "Yunnan", "Zhejiang"
    ]
  },
  brazil: {
    name: "Brazil",
    svg:  "svg/brazil.svg",
    regions: [
      "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia",
      "Ceará", "Distrito Federal", "Espírito Santo", "Goiás",
      "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais",
      "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí",
      "Rio Grande do Norte", "Rio Grande do Sul", "Rio de Janeiro",
      "Rondônia", "Roraima", "Santa Catarina", "Sergipe",
      "São Paulo", "Tocantins"
    ]
  },
  spain: {
    name: "Spain",
    svg:  "svg/spain.svg",
    regions: [
      "Andalusia", "Aragon", "Asturias", "Balearic Islands",
      "Basque Country", "Canary Islands", "Cantabria",
      "Castile and Leon", "Castile-La Mancha", "Catalonia",
      "Extremadura", "Galicia", "La Rioja", "Madrid",
      "Murcia", "Navarre", "Valencia"
    ]
  },
  uae: {
    name: "UAE",
    svg:  "svg/uae.svg",
    regions: [
      "Abu Dhabi", "Ajman", "Dubai",
      "Fujairah", "Ras al-Khaimah", "Sharjah", "Umm al-Quwain"
    ]
  },
  argentina: {
    name: "Argentina",
    svg:  "svg/argentina.svg",
    regions: [
      "Buenos Aires", "Catamarca", "Chaco", "Chubut",
      "Ciudad de Buenos Aires", "Córdoba", "Corrientes", "Entre Ríos",
      "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza",
      "Misiones", "Neuquén", "Río Negro", "Salta",
      "San Juan", "San Luis", "Santa Cruz", "Santa Fe",
      "Santiago del Estero", "Tierra del Fuego", "Tucumán"
    ]
  },
  france: {
    name: "France",
    svg:  "svg/france.svg",
    regions: [
      "Auvergne Rhône Alpes", "Bourgogne Franche Comté", "Bretagne",
      "Centre Val de Loire", "Corse", "Grand Est",
      "Hauts de France", "Île de France", "Normandie",
      "Nouvelle Aquitaine", "Occitanie", "Pays de la Loire",
      "Provence Alpes Côte d'Azu"
    ]
  },
  indonesia: {
    name: "Indonesia",
    svg:  "svg/indonesia.svg",
    regions: [
      "Aceh", "Bali", "Bangka-Belitung", "Banten", "Bengkulu",
      "Gorontalo", "Jakarta Raya", "Jambi", "Jawa Barat",
      "Jawa Tengah", "Jawa Timur", "Kalimantan Barat",
      "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Timur",
      "Kepulauan Riau", "Lampung", "Maluku", "Maluku Utara",
      "North Kalimantan", "Nusa Tenggara Barat", "Nusa Tenggara Timur",
      "Papua", "Papua Barat", "Riau", "Sulawesi Barat",
      "Sulawesi Selatan", "Sulawesi Tengah", "Sulawesi Tenggara",
      "Sulawesi Utara", "Sumatera Barat", "Sumatera Selatan",
      "Sumatera Utara", "Yogyakarta"
    ]
  },
  italy: {
    name: "Italy",
    svg:  "svg/italy.svg",
    regions: [
      "Abruzzo", "Basilicata", "Calabria", "Campania",
      "Emilia-Romagna", "Friuli Venezia Giulia", "Lazio", "Liguria",
      "Lombardy", "Marche", "Molise", "Piedmont",
      "Puglia", "Sardegna", "Sicilia", "Trentino-Alto Adige",
      "Tuscany", "Umbria", "Valle d'Aosta", "Veneto"
    ]
  },
  mexico: {
    name: "Mexico",
    svg:  "svg/mexico.svg",
    regions: [
      "Aguascalientes", "Baja California", "Baja California Sur",
      "Campeche", "Chiapas", "Chihuahua", "Coahuila",
      "Colima", "Durango", "Guanajuato", "Guerrero",
      "Hidalgo", "Jalisco", "Ciudad de México", "México",
      "Michoacán", "Morelos", "Nayarit", "Nuevo León",
      "Oaxaca", "Puebla", "Querétaro", "Quintana Roo",
      "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco",
      "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"
    ]
  },
  nigeria: {
    name: "Nigeria",
    svg:  "svg/nigeria.svg",
    regions: [
      "Abia", "Adamawa", "Akwa Ibom", "Anambra",
      "Bauchi", "Bayelsa", "Benue", "Borno",
      "Cross River", "Delta", "Ebonyi", "Edo",
      "Ekiti", "Enugu", "Federal Capital Territory", "Gombe",
      "Imo", "Jigawa", "Kaduna", "Kano",
      "Katsina", "Kebbi", "Kogi", "Kwara",
      "Lagos", "Nassarawa", "Niger", "Ogun",
      "Ondo", "Osun", "Oyo", "Plateau",
      "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"
    ]
  },
  pakistan: {
    name: "Pakistan",
    svg:  "svg/pakistan.svg",
    regions: [
      "Azad Kashmir", "Baluchistan", "F.C.T.",
      "K.P.", "Northern Areas", "Punjab", "Sind"
    ]
  },
  russia: {
    name: "Russia",
    svg:  "svg/russia.svg",
    regions: [
      "Adygey", "Altay", "Amur", "Arkhangel'sk", "Astrakhan'",
      "Bashkortostan", "Belgorod", "Bryansk", "Buryat", "Chechnya",
      "Chelyabinsk", "Chita", "Chukchi Autonomous Okrug", "Chuvash",
      "City of St. Petersburg", "Dagestan", "Gorno-Altay", "Ingush",
      "Irkutsk", "Ivanovo", "Kabardin-Balkar", "Kaliningrad", "Kalmyk",
      "Kaluga", "Kamchatka", "Karachay-Cherkess", "Karelia", "Kemerovo",
      "Khabarovsk", "Khakass", "Khanty-Mansiy", "Kirov", "Komi",
      "Kostroma", "Krasnodar", "Krasnoyarsk", "Kurgan", "Kursk",
      "Leningrad", "Lipetsk", "Maga Buryatdan", "Mariy-El", "Mordovia",
      "Moskovskaya", "Moskva", "Murmansk", "Nenets", "Nizhegorod",
      "North Ossetia", "Novgorod", "Novosibirsk", "Omsk", "Orel",
      "Orenburg", "Penza", "Perm'", "Primor'ye", "Pskov",
      "Rostov", "Ryazan'", "Sakha (Yakutia)", "Sakhalin", "Samara",
      "Saratov", "Smolensk", "Stavropol'", "Sverdlovsk", "Tambov",
      "Tatarstan", "Tomsk", "Tula", "Tuva", "Tver'",
      "Tyumen'", "Udmurt", "Ul'yanovsk", "Vladimir", "Volgograd",
      "Vologda", "Voronezh", "Yamal-Nenets", "Yaroslavl'", "Yevrey"
    ]
  },
  southKorea: {
    name: "South Korea",
    svg:  "svg/south_korea.svg",
    regions: [
      "Busan", "Daegu", "Daejeon", "Gangwon",
      "Gwangju", "Gyeonggi", "Incheon", "Jeju",
      "North Chungcheong", "North Gyeongsang", "North Jeolla",
      "Sejong", "Seoul", "South Chungcheong",
      "South Gyeongsang", "South Jeolla", "Ulsan"
    ]
  },
  turkey: {
    name: "Turkey",
    svg:  "svg/turkey.svg",
    regions: [
      "Adana", "Adiyaman", "Afyonkarahisar", "Agri",
      "Aksaray", "Amasya", "Ankara", "Antalya",
      "Ardahan", "Artvin", "Aydin", "Balikesir",
      "Bartın", "Batman", "Bayburt", "Bilecik",
      "Bingöl", "Bitlis", "Bolu", "Burdur",
      "Bursa", "Çanakkale", "Çankiri", "Çorum",
      "Denizli", "Diyarbakir", "Düzce", "Edirne",
      "Elazig", "Erzincan", "Erzurum", "Eskisehir",
      "Gaziantep", "Giresun", "Gümüshane", "Hakkari",
      "Hatay", "Iğdir", "Isparta", "Istanbul",
      "Izmir", "K. Maras", "Karabük", "Karaman",
      "Kars", "Kastamonu", "Kayseri", "Kilis",
      "Kinkkale", "Kirklareli", "Kirsehir", "Kocaeli",
      "Konya", "Kütahya", "Malatya", "Manisa",
      "Mardin", "Mersin", "Mugla", "Mus",
      "Nevsehir", "Nigde", "Ordu", "Osmaniye",
      "Rize", "Sakarya", "Samsun", "Sanliurfa",
      "Siirt", "Sinop", "Sirnak", "Sivas",
      "Tekirdag", "Tokat", "Trabzon", "Tunceli",
      "Usak", "Van", "Yalova", "Yozgat", "Zinguldak"
    ]
  },
  egypt: {
    name: "Egypt",
    svg:  "svg/egypt.svg",
    regions: [
      "Shamal Sina'", "Aswan", "Al Bahr al Ahmar", "Matruh",
      "Al Wadi at Jadid", "As Suways", "Janub Sina'", "Bur Sa`id",
      "Ad Daqahliyah", "Ash Sharqiyah", "Al Isma`iliyah", "Dumyat",
      "Kafr ash Shaykh", "Al Buhayrah", "Al Iskandariyah", "Al Qahirah",
      "Al Jizah", "Al Minya", "Al Fayyum", "Bani Suwayf",
      "Al Minufiyah", "Al Qalyubiyah", "Al Gharbiyah", "Suhaj",
      "Qina", "Asyut", "Luxor"
    ]
  },
  southAfrica: {
    name: "South Africa",
    svg:  "svg/south_africa.svg",
    regions: [
      "Northern Cape", "KwaZulu-Natal", "Free State", "Eastern Cape",
      "Limpopo", "North West", "Mpumalanga", "Western Cape", "Gauteng"
    ]
  },
  thailand: {
    name: "Thailand",
    svg:  "svg/thailand.svg",
    regions: [
      "Surin", "Si Sa Ket", "Ubon Ratchathani", "Sa Kaeo",
      "Buri Ram", "Trat", "Chanthaburi", "Satun",
      "Songkhla", "Yala", "Narathiwat", "Chiang Rai",
      "Chiang Mai", "Mae Hong Son", "Tak", "Kanchanaburi",
      "Prachuap Khiri Khan", "Phetchaburi", "Ratchaburi", "Chumphon",
      "Ranong", "Phayao", "Nan", "Uttaradit",
      "Phitsanulok", "Loei", "Bueng Kan", "Nong Khai",
      "Nakhon Phanom", "Mukdahan", "Amnat Charoen", "Phangnga",
      "Krabi", "Trang", "Pattani", "Phatthalung",
      "Nakhon Si Thammarat", "Surat Thani", "Samut Songkhram", "Samut Sakhon",
      "Bangkok Metropolis", "Samut Prakan", "Chachoengsao", "Phatthaya",
      "Rayong", "Phuket", "Khon Kaen", "Sakon Nakhon",
      "Suphan Buri", "Sing Buri", "Chai Nat", "Ang Thong",
      "Saraburi", "Nakhon Ratchasima", "Nakhon Nayok", "Pathum Thani",
      "Uthai Thani", "Kalasin", "Roi Et", "Maha Sarakham",
      "Nong Bua Lam Phu", "Lop Buri", "Udon Thani", "Phra Nakhon Si Ayutthaya",
      "Nonthaburi", "Nakhon Pathom", "Kamphaeng Phet", "Lampang",
      "Sukhothai", "Nakhon Sawan", "Phetchabun", "Phichit",
      "Chaiyaphum", "Phrae", "Lamphun", "Prachin Buri",
      "Yasothon", "Chon Buri"
    ]
  },
  vietnam: {
    name: "Vietnam",
    svg:  "svg/vietnam.svg",
    regions: [
      "Kon Tum", "Đắk Nông", "Đắk Lắk", "Gia Lai",
      "Bình Phước", "Tây Ninh", "Long An", "Ðong Tháp",
      "An Giang", "Kiên Giang", "Điện Biên", "Son La",
      "Thanh Hóa", "Nghệ An", "Ha Tinh", "Quảng Bình",
      "Quảng Trị", "Thừa Thiên - Huế", "Quàng Nam", "Hà Giang",
      "Cao Bằng", "Lào Cai", "Lai Chau", "Lạng Sơn",
      "Quảng Ninh", "Sóc Trăng", "Tiền Giang", "Bà Rịa - Vũng Tàu",
      "Hồ Chí Minh city", "Khánh Hòa", "Cà Mau", "Bạc Liêu",
      "Hau Giang", "Vĩnh Long", "Trà Vinh", "Bến Tre",
      "Đông Nam Bộ", "Bình Thuận", "Ninh Thuận", "Phú Yên",
      "Bình Định", "Quảng Ngãi", "Đà Nẵng", "Ninh Bình",
      "Nam Định", "Thái Bình", "Hải Phòng", "Hòa Bình",
      "Tuyên Quang", "Yên Bái", "Vĩnh Phúc", "Phú Thọ",
      "Ha Noi", "Đông Bắc", "Đồng Bằng Sông Hồng", "Bắc Ninh",
      "Bắc Giang", "Thái Nguyên", "Hải Dương", "Hà Nam",
      "Bình Dương", "Lâm Đồng", "Can Tho"
    ]
  },
  greece: {
    name: "Greece",
    svg:  "svg/greece.svg",
    regions: [
      "Dytiki Makedonia", "Ipeiros", "Kentriki Makedonia",
      "Anatoliki Makedonia kai Thraki", "Ayion Oros", "Thessalia",
      "Stereá Elláda", "Attiki", "Peloponnisos",
      "Dytiki Ellada", "Kriti", "Notio Aigaio",
      "Voreio Aigaio", "Ionioi Nisoi"
    ]
  },
  europe: {
    name: "Europe",
    svg:  "svg/europe.svg",
    regions: [
      "Germany", "France", "Italy", "Spain", "Portugal",
      "Netherlands", "Belgium", "Luxembourg", "Switzerland", "Austria",
      "Poland", "Czech Republic", "Slovakia", "Hungary", "Romania",
      "Bulgaria", "Greece", "Croatia", "Slovenia", "Serbia",
      "Bosnia and Herzegovina", "Montenegro", "Albania", "Macedonia",
      "Sweden", "Norway", "Finland", "Denmark",
      "Estonia", "Latvia", "Lithuania",
      "Ireland", "United Kingdom",
      "Ukraine", "Belarus", "Moldova",
      "Russia", "Kazakhstan",
      "Turkey", "Cyprus", "Malta", "Iceland"
    ]
  },
  northAmerica: {
    name: "North America",
    svg:  "svg/north america.svg",
    regions: [
      "Canada", "United States", "Mexico",
      "Guatemala", "Belize", "El Salvador", "Honduras",
      "Nicaragua", "Costa Rica", "Panama",
      "Cuba", "Jamaica", "Haiti", "Dominican Republic",
      "Bahamas", "Barbados", "Trinidad and Tobago",
      "Saint Lucia", "Grenada", "Antigua and Barbuda",
      "Dominica", "Saint Kitts and Nevis", "Saint Vincent and the Grenadines"
    ]
  },
  southAmerica: {
    name: "South America",
    svg:  "svg/south america.svg",
    regions: [
      "Argentina", "Bolivia", "Brazil", "Chile",
      "Colombia", "Ecuador", "Guyana", "Paraguay",
      "Peru", "Suriname", "Uruguay", "Venezuela"
    ]
  },
  africa: {
    name: "Africa",
    svg:  "svg/africa.svg",
    regions: [
      "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso",
      "Burundi", "Cameroon", "Cape Verde", "Central African Republic", "Chad",
      "Comoros", "Democratic Republic of Congo", "Republic of Congo",
      "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Swaziland",
      "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau",
      "Côte d'Ivoire", "Kenya", "Lesotho", "Liberia", "Libya",
      "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius",
      "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria",
      "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles",
      "Sierra Leone", "Somalia", "South Africa", "South Sudan",
      "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"
    ]
  },
  asia: {
    name: "Asia",
    svg:  "svg/asia.svg",
    regions: [
      "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh",
      "Bhutan", "Brunei", "Cambodia", "China", "Cyprus",
      "Georgia", "India", "Indonesia", "Iran", "Iraq",
      "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait",
      "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives",
      "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman",
      "Pakistan", "Palestine", "Philippines", "Qatar", "Saudi Arabia",
      "Singapore", "South Korea", "Sri Lanka", "Syria", "Taiwan",
      "Tajikistan", "Thailand", "Timor-Leste", "Turkey", "Turkmenistan",
      "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"
    ]
  },
  oceania: {
    name: "Oceania",
    svg:  "svg/oceania.svg",
    regions: [
      "Australia", "New Zealand", "Papua New Guinea", "Fiji",
      "Solomon Islands", "Vanuatu", "Samoa", "Tonga",
      "Kiribati", "Federated States of Micronesia", "Palau", "Marshall Islands",
      "Nauru", "Tuvalu"
    ]
  },
  world: {
    name: "World",
    svg:  "svg/world.svg",
    regions: [
      "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
      "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
      "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
      "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
      "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
      "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
      "Cameroon", "Canada", "Central African Republic", "Chad", "Chile",
      "China", "Colombia", "Comoros", "Congo", "Costa Rica",
      "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark",
      "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
      "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
      "Ethiopia", "Fiji", "Finland", "France", "Gabon",
      "Gambia", "Georgia", "Germany", "Ghana", "Greece",
      "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
      "Haiti", "Honduras", "Hungary", "Iceland", "India",
      "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
      "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan",
      "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos",
      "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
      "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi",
      "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
      "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
      "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
      "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
      "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea",
      "North Macedonia", "Norway", "Oman", "Pakistan", "Palau",
      "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru",
      "Philippines", "Poland", "Portugal", "Qatar", "Romania",
      "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
      "Saint Vincent and the Grenadines", "Samoa", "San Marino",
      "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
      "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
      "Solomon Islands", "Somalia", "South Africa", "South Korea",
      "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname",
      "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
      "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga",
      "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
      "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
      "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City",
      "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    ]
  }
};

/* ============================================================
   FLAGS DATASET — country name -> flag emoji
   ============================================================ */
const FLAGS = {
  // World countries
  "Afghanistan": "🇦🇫", "Albania": "🇦🇱", "Algeria": "🇩🇿", "Argentina": "🇦🇷",
  "Australia": "🇦🇺", "Austria": "🇦🇹", "Bangladesh": "🇧🇩", "Belgium": "🇧🇪",
  "Bolivia": "🇧🇴", "Brazil": "🇧🇷", "Canada": "🇨🇦", "Chile": "🇨🇱",
  "China": "🇨🇳", "Colombia": "🇨🇴", "Croatia": "🇭🇷", "Cuba": "🇨🇺",
  "Czech Republic": "🇨🇿", "Denmark": "🇩🇰", "Ecuador": "🇪🇨", "Egypt": "🇪🇬",
  "Ethiopia": "🇪🇹", "Finland": "🇫🇮", "France": "🇫🇷", "Germany": "🇩🇪",
  "Ghana": "🇬🇭", "Greece": "🇬🇷", "Hungary": "🇭🇺", "Iceland": "🇮🇸",
  "India": "🇮🇳", "Indonesia": "🇮🇩", "Iran": "🇮🇷", "Iraq": "🇮🇶",
  "Ireland": "🇮🇪", "Israel": "🇮🇱", "Italy": "🇮🇹", "Jamaica": "🇯🇲",
  "Japan": "🇯🇵", "Jordan": "🇯🇴", "Kazakhstan": "🇰🇿", "Kenya": "🇰🇪",
  "Kuwait": "🇰🇼", "Lebanon": "🇱🇧", "Libya": "🇱🇾", "Malaysia": "🇲🇾",
  "Mexico": "🇲🇽", "Mongolia": "🇲🇳", "Morocco": "🇲🇦", "Myanmar": "🇲🇲",
  "Nepal": "🇳🇵", "Netherlands": "🇳🇱", "New Zealand": "🇳🇿", "Nigeria": "🇳🇬",
  "North Korea": "🇰🇵", "Norway": "🇳🇴", "Pakistan": "🇵🇰", "Peru": "🇵🇪",
  "Philippines": "🇵🇭", "Poland": "🇵🇱", "Portugal": "🇵🇹", "Qatar": "🇶🇦",
  "Romania": "🇷🇴", "Russia": "🇷🇺", "Saudi Arabia": "🇸🇦", "Serbia": "🇷🇸",
  "Singapore": "🇸🇬", "South Africa": "🇿🇦", "South Korea": "🇰🇷", "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰", "Sweden": "🇸🇪", "Switzerland": "🇨🇭", "Syria": "🇸🇾",
  "Taiwan": "🇹🇼", "Thailand": "🇹🇭", "Turkey": "🇹🇷", "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪", "United Kingdom": "🇬🇧", "United States": "🇺🇸",
  "Uruguay": "🇺🇾", "Venezuela": "🇻🇪", "Vietnam": "🇻🇳", "Yemen": "🇾🇪",
  "Zambia": "🇿🇲", "Zimbabwe": "🇿🇼",
  // Europe
  "Luxembourg": "🇱🇺", "Bulgaria": "🇧🇬", "Slovakia": "🇸🇰", "Slovenia": "🇸🇮",
  "Belarus": "🇧🇾", "Lithuania": "🇱🇹", "Latvia": "🇱🇻", "Estonia": "🇪🇪",
  "Moldova": "🇲🇩", "Montenegro": "🇲🇪", "Bosnia and Herzegovina": "🇧🇦",
  "Albania": "🇦🇱", "North Macedonia": "🇲🇰", "Cyprus": "🇨🇾", "Malta": "🇲🇹",
  // Americas
  "Guatemala": "🇬🇹", "Honduras": "🇭🇳", "Nicaragua": "🇳🇮", "Costa Rica": "🇨🇷",
  "Panama": "🇵🇦", "Haiti": "🇭🇹", "Dominican Republic": "🇩🇴", "Bahamas": "🇧🇸",
  "Trinidad and Tobago": "🇹🇹", "Paraguay": "🇵🇾", "Guyana": "🇬🇾",
  "Suriname": "🇸🇷",
  // Africa
  "Tunisia": "🇹🇳", "Sudan": "🇸🇩", "Angola": "🇦🇴", "Mozambique": "🇲🇿",
  "Madagascar": "🇲🇬", "Cameroon": "🇨🇲", "Niger": "🇳🇪", "Mali": "🇲🇱",
  "Senegal": "🇸🇳", "Uganda": "🇺🇬", "Tanzania": "🇹🇿", "Rwanda": "🇷🇼",
  // Asia/Oceania
  "Bhutan": "🇧🇹", "Cambodia": "🇰🇭", "Laos": "🇱🇦", "Brunei": "🇧🇳",
  "Papua New Guinea": "🇵🇬", "Fiji": "🇫🇯"
};

/* ============================================================
   CAPITALS DATASET
   ============================================================ */
const CAPITALS = {
  world: {
    "Afghanistan": "Kabul", "Albania": "Tirana", "Algeria": "Algiers",
    "Argentina": "Buenos Aires", "Australia": "Canberra", "Austria": "Vienna",
    "Bangladesh": "Dhaka", "Belgium": "Brussels", "Bolivia": "Sucre",
    "Brazil": "Brasília", "Canada": "Ottawa", "Chile": "Santiago",
    "China": "Beijing", "Colombia": "Bogotá", "Croatia": "Zagreb",
    "Cuba": "Havana", "Czech Republic": "Prague", "Denmark": "Copenhagen",
    "Ecuador": "Quito", "Egypt": "Cairo", "Ethiopia": "Addis Ababa",
    "Finland": "Helsinki", "France": "Paris", "Germany": "Berlin",
    "Ghana": "Accra", "Greece": "Athens", "Hungary": "Budapest",
    "Iceland": "Reykjavik", "India": "New Delhi", "Indonesia": "Jakarta",
    "Iran": "Tehran", "Iraq": "Baghdad", "Ireland": "Dublin",
    "Israel": "Jerusalem", "Italy": "Rome", "Jamaica": "Kingston",
    "Japan": "Tokyo", "Jordan": "Amman", "Kazakhstan": "Astana",
    "Kenya": "Nairobi", "Kuwait": "Kuwait City", "Lebanon": "Beirut",
    "Libya": "Tripoli", "Malaysia": "Kuala Lumpur", "Mexico": "Mexico City",
    "Mongolia": "Ulaanbaatar", "Morocco": "Rabat", "Myanmar": "Naypyidaw",
    "Nepal": "Kathmandu", "Netherlands": "Amsterdam", "New Zealand": "Wellington",
    "Nigeria": "Abuja", "North Korea": "Pyongyang", "Norway": "Oslo",
    "Pakistan": "Islamabad", "Peru": "Lima", "Philippines": "Manila",
    "Poland": "Warsaw", "Portugal": "Lisbon", "Qatar": "Doha",
    "Romania": "Bucharest", "Russia": "Moscow", "Saudi Arabia": "Riyadh",
    "Serbia": "Belgrade", "Singapore": "Singapore", "South Africa": "Pretoria",
    "South Korea": "Seoul", "Spain": "Madrid", "Sri Lanka": "Sri Jayawardenepura Kotte",
    "Sweden": "Stockholm", "Switzerland": "Bern", "Syria": "Damascus",
    "Thailand": "Bangkok", "Turkey": "Ankara", "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi", "United Kingdom": "London",
    "United States": "Washington D.C.", "Uruguay": "Montevideo",
    "Venezuela": "Caracas", "Vietnam": "Hanoi", "Yemen": "Sanaa",
    "Zambia": "Lusaka", "Zimbabwe": "Harare"
  },
  india: {
    // 28 States — keys match SVG name attributes exactly
    "Andhra Pradesh": "Amaravati",     "Arunachal Pradesh": "Itanagar",
    "Assam": "Dispur",                 "Bihar": "Patna",
    "Chhattisgarh": "Raipur",          "Goa": "Panaji",
    "Gujarat": "Gandhinagar",          "Haryana": "Chandigarh",
    "Himachal Pradesh": "Shimla",      "Jharkhand": "Ranchi",
    "Karnataka": "Bengaluru",          "Kerala": "Thiruvananthapuram",
    "Madhya Pradesh": "Bhopal",        "Maharashtra": "Mumbai",
    "Manipur": "Imphal",               "Meghalaya": "Shillong",
    "Mizoram": "Aizawl",               "Nagaland": "Kohima",
    "Odisha": "Bhubaneswar",           "Punjab": "Chandigarh",
    "Rajasthan": "Jaipur",             "Sikkim": "Gangtok",
    "Tamil Nadu": "Chennai",           "Telangana": "Hyderabad",
    "Tripura": "Agartala",             "Uttar Pradesh": "Lucknow",
    "Uttarakhand": "Dehradun",         "West Bengal": "Kolkata",
    // 8 Union Territories — also in SVG
    "Andaman and Nicobar Islands": "Port Blair",
    "Chandigarh": "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu": "Daman",
    "Delhi": "New Delhi",
    "Jammu and Kashmir": "Srinagar",
    "Ladakh": "Leh",
    "Lakshadweep": "Kavaratti",
    "Puducherry": "Puducherry"
  },
  usa: {
    "Alabama": "Montgomery", "Alaska": "Juneau", "Arizona": "Phoenix",
    "Arkansas": "Little Rock", "California": "Sacramento",
    "Colorado": "Denver", "Connecticut": "Hartford", "Delaware": "Dover",
    "Florida": "Tallahassee", "Georgia": "Atlanta", "Hawaii": "Honolulu",
    "Idaho": "Boise", "Illinois": "Springfield", "Indiana": "Indianapolis",
    "Iowa": "Des Moines", "Kansas": "Topeka", "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge", "Maine": "Augusta", "Maryland": "Annapolis",
    "Massachusetts": "Boston", "Michigan": "Lansing", "Minnesota": "Saint Paul",
    "Mississippi": "Jackson", "Missouri": "Jefferson City",
    "Montana": "Helena", "Nebraska": "Lincoln", "Nevada": "Carson City",
    "New Hampshire": "Concord", "New Jersey": "Trenton",
    "New Mexico": "Santa Fe", "New York": "Albany",
    "North Carolina": "Raleigh", "North Dakota": "Bismarck",
    "Ohio": "Columbus", "Oklahoma": "Oklahoma City", "Oregon": "Salem",
    "Pennsylvania": "Harrisburg", "Rhode Island": "Providence",
    "South Carolina": "Columbia", "South Dakota": "Pierre",
    "Tennessee": "Nashville", "Texas": "Austin", "Utah": "Salt Lake City",
    "Vermont": "Montpelier", "Virginia": "Richmond",
    "Washington": "Olympia", "West Virginia": "Charleston",
    "Wisconsin": "Madison", "Wyoming": "Cheyenne"
  },
  canada: {
    "Alberta": "Edmonton",
    "British Columbia": "Victoria",
    "Manitoba": "Winnipeg",
    "New Brunswick": "Fredericton",
    "Newfoundland and Labrador": "St. John's",
    "Northwest Territories": "Yellowknife",
    "Nova Scotia": "Halifax",
    "Nunavut": "Iqaluit",
    "Ontario": "Toronto",
    "Prince Edward Island": "Charlottetown",
    "Quebec": "Quebec City",
    "Saskatchewan": "Regina",
    "Yukon": "Whitehorse"
  },
  australia: {
    "Australian Capital Territory": "Canberra",
    "New South Wales": "Sydney",
    "Northern Territory": "Darwin",
    "Queensland": "Brisbane",
    "South Australia": "Adelaide",
    "Tasmania": "Hobart",
    "Victoria": "Melbourne",
    "Western Australia": "Perth"
  },
  japan: {
    "Aichi": "Nagoya",       "Akita": "Akita",        "Aomori": "Aomori",
    "Chiba": "Chiba",        "Ehime": "Matsuyama",    "Fukui": "Fukui",
    "Fukuoka": "Fukuoka",    "Fukushima": "Fukushima", "Gifu": "Gifu",
    "Gunma": "Maebashi",     "Hiroshima": "Hiroshima", "Hokkaido": "Sapporo",
    "Hyogo": "Kobe",         "Ibaraki": "Mito",        "Ishikawa": "Kanazawa",
    "Iwate": "Morioka",      "Kagawa": "Takamatsu",   "Kagoshima": "Kagoshima",
    "Kanagawa": "Yokohama",  "Kochi": "Kochi",         "Kumamoto": "Kumamoto",
    "Kyoto": "Kyoto",        "Mie": "Tsu",             "Miyagi": "Sendai",
    "Miyazaki": "Miyazaki",  "Nagano": "Nagano",       "Nagasaki": "Nagasaki",
    "Nara": "Nara",          "Niigata": "Niigata",     "Oita": "Oita",
    "Okayama": "Okayama",    "Okinawa": "Naha",        "Osaka": "Osaka",
    "Saga": "Saga",          "Saitama": "Saitama",     "Shiga": "Otsu",
    "Shimane": "Matsue",     "Shizuoka": "Shizuoka",   "Tochigi": "Utsunomiya",
    "Tokushima": "Tokushima","Tokyo": "Tokyo",          "Tottori": "Tottori",
    "Toyama": "Toyama",      "Wakayama": "Wakayama",   "Yamagata": "Yamagata",
    "Yamaguchi": "Yamaguchi","Yamanashi": "Kofu"
  },
  germany: {
    "Baden-Wurttemberg": "Stuttgart",
    "Bavaria": "Munich",
    "Berlin": "Berlin",
    "Brandenburg": "Potsdam",
    "Bremen": "Bremen",
    "Hamburg": "Hamburg",
    "Hesse": "Wiesbaden",
    "Lower Saxony": "Hanover",
    "Mecklenburg-Vorpommern": "Schwerin",
    "North Rhine-Westphalia": "Düsseldorf",
    "Rhineland-Palatinate": "Mainz",
    "Saarland": "Saarbrücken",
    "Saxony": "Dresden",
    "Saxony-Anhalt": "Magdeburg",
    "Schleswig-Holstein": "Kiel",
    "Thuringia": "Erfurt"
  },
  china: {
    "Anhui": "Hefei",              "Beijing": "Beijing",
    "Chongqing": "Chongqing",      "Fujian": "Fuzhou",
    "Gansu": "Lanzhou",            "Guangdong": "Guangzhou",
    "Guangxi Zhuang": "Nanning",   "Guizhou": "Guiyang",
    "Hainan": "Haikou",            "Hebei": "Shijiazhuang",
    "Heilongjiang": "Harbin",      "Henan": "Zhengzhou",
    "Hong Kong": "Hong Kong",      "Hubei": "Wuhan",
    "Hunan": "Changsha",           "Jiangsu": "Nanjing",
    "Jiangxi": "Nanchang",         "Jilin": "Changchun",
    "Liaoning": "Shenyang",        "Macau": "Macau",
    "Nei Mongol": "Hohhot",        "Ningxia Hui": "Yinchuan",
    "Qinghai": "Xining",           "Shaanxi": "Xi'an",
    "Shandong": "Jinan",           "Shanghai": "Shanghai",
    "Shanxi": "Taiyuan",           "Sichuan": "Chengdu",
    "Tianjin": "Tianjin",          "Xinjiang Uygur": "Ürümqi",
    "Xizang (Tibet)": "Lhasa",     "Yunnan": "Kunming",
    "Zhejiang": "Hangzhou"
  },
  brazil: {
    "Acre": "Rio Branco",
    "Alagoas": "Maceió",
    "Amapá": "Macapá",
    "Amazonas": "Manaus",
    "Bahia": "Salvador",
    "Ceará": "Fortaleza",
    "Distrito Federal": "Brasília",
    "Espírito Santo": "Vitória",
    "Goiás": "Goiânia",
    "Maranhão": "São Luís",
    "Mato Grosso": "Cuiabá",
    "Mato Grosso do Sul": "Campo Grande",
    "Minas Gerais": "Belo Horizonte",
    "Pará": "Belém",
    "Paraíba": "João Pessoa",
    "Paraná": "Curitiba",
    "Pernambuco": "Recife",
    "Piauí": "Teresina",
    "Rio Grande do Norte": "Natal",
    "Rio Grande do Sul": "Porto Alegre",
    "Rio de Janeiro": "Rio de Janeiro",
    "Rondônia": "Porto Velho",
    "Roraima": "Boa Vista",
    "Santa Catarina": "Florianópolis",
    "Sergipe": "Aracaju",
    "São Paulo": "São Paulo",
    "Tocantins": "Palmas"
  },
  spain: {
    "Andalusia": "Seville",
    "Aragon": "Zaragoza",
    "Asturias": "Oviedo",
    "Balearic Islands": "Palma",
    "Basque Country": "Vitoria-Gasteiz",
    "Canary Islands": "Las Palmas / Santa Cruz de Tenerife",
    "Cantabria": "Santander",
    "Castile and Leon": "Valladolid",
    "Castile-La Mancha": "Toledo",
    "Catalonia": "Barcelona",
    "Extremadura": "Mérida",
    "Galicia": "Santiago de Compostela",
    "La Rioja": "Logroño",
    "Madrid": "Madrid",
    "Murcia": "Murcia",
    "Navarre": "Pamplona",
    "Valencia": "Valencia"
  },
  argentina: {
    "Buenos Aires": "Buenos Aires",
    "Catamarca": "San Fernando del Valle de Catamarca",
    "Chaco": "Resistencia",         "Chubut": "Rawson",
    "Ciudad de Buenos Aires": "Buenos Aires",
    "Córdoba": "Córdoba",           "Corrientes": "Corrientes",
    "Entre Ríos": "Paraná",         "Formosa": "Formosa",
    "Jujuy": "San Salvador de Jujuy","La Pampa": "Santa Rosa",
    "La Rioja": "La Rioja",         "Mendoza": "Mendoza",
    "Misiones": "Posadas",          "Neuquén": "Neuquén",
    "Río Negro": "Viedma",          "Salta": "Salta",
    "San Juan": "San Juan",         "San Luis": "San Luis",
    "Santa Cruz": "Río Gallegos",   "Santa Fe": "Santa Fe",
    "Santiago del Estero": "Santiago del Estero",
    "Tierra del Fuego": "Ushuaia",  "Tucumán": "San Miguel de Tucumán"
  },
  france: {
    "Auvergne Rhône Alpes": "Lyon",
    "Bourgogne Franche Comté": "Dijon",
    "Bretagne": "Rennes",
    "Centre Val de Loire": "Orléans",
    "Corse": "Ajaccio",
    "Grand Est": "Strasbourg",
    "Hauts de France": "Lille",
    "Île de France": "Paris",
    "Normandie": "Rouen",
    "Nouvelle Aquitaine": "Bordeaux",
    "Occitanie": "Toulouse",
    "Pays de la Loire": "Nantes",
    "Provence Alpes Côte d'Azu": "Marseille"
  },
  indonesia: {
    "Aceh": "Banda Aceh",                 "Bali": "Denpasar",
    "Bangka-Belitung": "Pangkal Pinang",  "Banten": "Serang",
    "Bengkulu": "Bengkulu",               "Gorontalo": "Gorontalo",
    "Jakarta Raya": "Jakarta",            "Jambi": "Jambi",
    "Jawa Barat": "Bandung",              "Jawa Tengah": "Semarang",
    "Jawa Timur": "Surabaya",             "Kalimantan Barat": "Pontianak",
    "Kalimantan Selatan": "Banjarbaru",   "Kalimantan Tengah": "Palangka Raya",
    "Kalimantan Timur": "Samarinda",      "Kepulauan Riau": "Tanjungpinang",
    "Lampung": "Bandar Lampung",          "Maluku": "Ambon",
    "Maluku Utara": "Sofifi",             "North Kalimantan": "Tanjung Selor",
    "Nusa Tenggara Barat": "Mataram",     "Nusa Tenggara Timur": "Kupang",
    "Papua": "Jayapura",                  "Papua Barat": "Manokwari",
    "Riau": "Pekanbaru",                  "Sulawesi Barat": "Mamuju",
    "Sulawesi Selatan": "Makassar",       "Sulawesi Tengah": "Palu",
    "Sulawesi Tenggara": "Kendari",       "Sulawesi Utara": "Manado",
    "Sumatera Barat": "Padang",           "Sumatera Selatan": "Palembang",
    "Sumatera Utara": "Medan",            "Yogyakarta": "Yogyakarta"
  },
  italy: {
    "Abruzzo": "L'Aquila",            "Basilicata": "Potenza",
    "Calabria": "Catanzaro",          "Campania": "Naples",
    "Emilia-Romagna": "Bologna",      "Friuli Venezia Giulia": "Trieste",
    "Lazio": "Rome",                  "Liguria": "Genoa",
    "Lombardy": "Milan",              "Marche": "Ancona",
    "Molise": "Campobasso",           "Piedmont": "Turin",
    "Puglia": "Bari",                 "Sardegna": "Cagliari",
    "Sicilia": "Palermo",             "Trentino-Alto Adige": "Trento",
    "Tuscany": "Florence",            "Umbria": "Perugia",
    "Valle d'Aosta": "Aosta",         "Veneto": "Venice"
  },
  mexico: {
    "Aguascalientes": "Aguascalientes", "Baja California": "Mexicali",
    "Baja California Sur": "La Paz",    "Campeche": "Campeche",
    "Chiapas": "Tuxtla Gutiérrez",      "Chihuahua": "Chihuahua",
    "Coahuila": "Saltillo",             "Colima": "Colima",
    "Durango": "Durango",               "Guanajuato": "Guanajuato",
    "Guerrero": "Chilpancingo",         "Hidalgo": "Pachuca",
    "Jalisco": "Guadalajara",           "Ciudad de México": "Mexico City",
    "México": "Toluca",                 "Michoacán": "Morelia",
    "Morelos": "Cuernavaca",            "Nayarit": "Tepic",
    "Nuevo León": "Monterrey",          "Oaxaca": "Oaxaca",
    "Puebla": "Puebla",                 "Querétaro": "Querétaro",
    "Quintana Roo": "Chetumal",         "San Luis Potosí": "San Luis Potosí",
    "Sinaloa": "Culiacán",              "Sonora": "Hermosillo",
    "Tabasco": "Villahermosa",          "Tamaulipas": "Ciudad Victoria",
    "Tlaxcala": "Tlaxcala",             "Veracruz": "Xalapa",
    "Yucatán": "Mérida",                "Zacatecas": "Zacatecas"
  },
  nigeria: {
    "Abia": "Umuahia",                    "Adamawa": "Yola",
    "Akwa Ibom": "Uyo",                   "Anambra": "Awka",
    "Bauchi": "Bauchi",                   "Bayelsa": "Yenagoa",
    "Benue": "Makurdi",                   "Borno": "Maiduguri",
    "Cross River": "Calabar",             "Delta": "Asaba",
    "Ebonyi": "Abakaliki",                "Edo": "Benin City",
    "Ekiti": "Ado-Ekiti",                 "Enugu": "Enugu",
    "Federal Capital Territory": "Abuja", "Gombe": "Gombe",
    "Imo": "Owerri",                      "Jigawa": "Dutse",
    "Kaduna": "Kaduna",                   "Kano": "Kano",
    "Katsina": "Katsina",                 "Kebbi": "Birnin Kebbi",
    "Kogi": "Lokoja",                     "Kwara": "Ilorin",
    "Lagos": "Ikeja",                     "Nassarawa": "Lafia",
    "Niger": "Minna",                     "Ogun": "Abeokuta",
    "Ondo": "Akure",                      "Osun": "Osogbo",
    "Oyo": "Ibadan",                      "Plateau": "Jos",
    "Rivers": "Port Harcourt",            "Sokoto": "Sokoto",
    "Taraba": "Jalingo",                  "Yobe": "Damaturu",
    "Zamfara": "Gusau"
  },
  pakistan: {
    "Azad Kashmir": "Muzaffarabad",
    "Baluchistan": "Quetta",
    "F.C.T.": "Islamabad",
    "K.P.": "Peshawar",
    "Northern Areas": "Gilgit",
    "Punjab": "Lahore",
    "Sind": "Karachi"
  },
  russia: {
    "Adygey": "Maykop",                   "Altay": "Barnaul",
    "Amur": "Blagoveshchensk",            "Arkhangel'sk": "Arkhangelsk",
    "Astrakhan'": "Astrakhan",            "Bashkortostan": "Ufa",
    "Belgorod": "Belgorod",               "Bryansk": "Bryansk",
    "Buryat": "Ulan-Ude",                 "Chechnya": "Grozny",
    "Chelyabinsk": "Chelyabinsk",         "Chita": "Chita",
    "Chukchi Autonomous Okrug": "Anadyr", "Chuvash": "Cheboksary",
    "City of St. Petersburg": "Saint Petersburg",
    "Dagestan": "Makhachkala",            "Gorno-Altay": "Gorno-Altaysk",
    "Ingush": "Magas",                    "Irkutsk": "Irkutsk",
    "Ivanovo": "Ivanovo",                 "Kabardin-Balkar": "Nalchik",
    "Kaliningrad": "Kaliningrad",         "Kalmyk": "Elista",
    "Kaluga": "Kaluga",                   "Kamchatka": "Petropavlovsk-Kamchatsky",
    "Karachay-Cherkess": "Cherkessk",     "Karelia": "Petrozavodsk",
    "Kemerovo": "Kemerovo",               "Khabarovsk": "Khabarovsk",
    "Khakass": "Abakan",                  "Khanty-Mansiy": "Khanty-Mansiysk",
    "Kirov": "Kirov",                     "Komi": "Syktyvkar",
    "Kostroma": "Kostroma",               "Krasnodar": "Krasnodar",
    "Krasnoyarsk": "Krasnoyarsk",         "Kurgan": "Kurgan",
    "Kursk": "Kursk",                     "Leningrad": "Gatchina",
    "Lipetsk": "Lipetsk",                 "Maga Buryatdan": "Magadan",
    "Mariy-El": "Yoshkar-Ola",            "Mordovia": "Saransk",
    "Moskovskaya": "Krasnogorsk",         "Moskva": "Moscow",
    "Murmansk": "Murmansk",               "Nenets": "Naryan-Mar",
    "Nizhegorod": "Nizhny Novgorod",      "North Ossetia": "Vladikavkaz",
    "Novgorod": "Veliky Novgorod",        "Novosibirsk": "Novosibirsk",
    "Omsk": "Omsk",                       "Orel": "Oryol",
    "Orenburg": "Orenburg",               "Penza": "Penza",
    "Perm'": "Perm",                      "Primor'ye": "Vladivostok",
    "Pskov": "Pskov",                     "Rostov": "Rostov-on-Don",
    "Ryazan'": "Ryazan",                  "Sakha (Yakutia)": "Yakutsk",
    "Sakhalin": "Yuzhno-Sakhalinsk",      "Samara": "Samara",
    "Saratov": "Saratov",                 "Smolensk": "Smolensk",
    "Stavropol'": "Stavropol",            "Sverdlovsk": "Yekaterinburg",
    "Tambov": "Tambov",                   "Tatarstan": "Kazan",
    "Tomsk": "Tomsk",                     "Tula": "Tula",
    "Tuva": "Kyzyl",                      "Tver'": "Tver",
    "Tyumen'": "Tyumen",                  "Udmurt": "Izhevsk",
    "Ul'yanovsk": "Ulyanovsk",            "Vladimir": "Vladimir",
    "Volgograd": "Volgograd",             "Vologda": "Vologda",
    "Voronezh": "Voronezh",               "Yamal-Nenets": "Salekhard",
    "Yaroslavl'": "Yaroslavl",            "Yevrey": "Birobidzhan"
  },
  southKorea: {
    "Busan": "Busan",
    "Daegu": "Daegu",
    "Daejeon": "Daejeon",
    "Gangwon": "Chuncheon",
    "Gwangju": "Gwangju",
    "Gyeonggi": "Suwon",
    "Incheon": "Incheon",
    "Jeju": "Jeju City",
    "North Chungcheong": "Cheongju",
    "North Gyeongsang": "Andong",
    "North Jeolla": "Jeonju",
    "Sejong": "Sejong",
    "Seoul": "Seoul",
    "South Chungcheong": "Hongseong",
    "South Gyeongsang": "Changwon",
    "South Jeolla": "Muan",
    "Ulsan": "Ulsan"
  },
  turkey: {
    "Adana": "Adana",           "Adiyaman": "Adıyaman",
    "Afyonkarahisar": "Afyon",  "Agri": "Ağrı",
    "Aksaray": "Aksaray",       "Amasya": "Amasya",
    "Ankara": "Ankara",         "Antalya": "Antalya",
    "Ardahan": "Ardahan",       "Artvin": "Artvin",
    "Aydin": "Aydın",           "Balikesir": "Balıkesir",
    "Bartın": "Bartın",         "Batman": "Batman",
    "Bayburt": "Bayburt",       "Bilecik": "Bilecik",
    "Bingöl": "Bingöl",         "Bitlis": "Bitlis",
    "Bolu": "Bolu",             "Burdur": "Burdur",
    "Bursa": "Bursa",           "Çanakkale": "Çanakkale",
    "Çankiri": "Çankırı",       "Çorum": "Çorum",
    "Denizli": "Denizli",       "Diyarbakir": "Diyarbakır",
    "Düzce": "Düzce",           "Edirne": "Edirne",
    "Elazig": "Elazığ",         "Erzincan": "Erzincan",
    "Erzurum": "Erzurum",       "Eskisehir": "Eskişehir",
    "Gaziantep": "Gaziantep",   "Giresun": "Giresun",
    "Gümüshane": "Gümüşhane",   "Hakkari": "Hakkari",
    "Hatay": "Antakya",         "Iğdir": "Iğdır",
    "Isparta": "Isparta",       "Istanbul": "Istanbul",
    "Izmir": "Izmir",           "K. Maras": "Kahramanmaraş",
    "Karabük": "Karabük",       "Karaman": "Karaman",
    "Kars": "Kars",             "Kastamonu": "Kastamonu",
    "Kayseri": "Kayseri",       "Kilis": "Kilis",
    "Kinkkale": "Kırıkkale",    "Kirklareli": "Kırklareli",
    "Kirsehir": "Kırşehir",     "Kocaeli": "İzmit",
    "Konya": "Konya",           "Kütahya": "Kütahya",
    "Malatya": "Malatya",       "Manisa": "Manisa",
    "Mardin": "Mardin",         "Mersin": "Mersin",
    "Mugla": "Muğla",           "Mus": "Muş",
    "Nevsehir": "Nevşehir",     "Nigde": "Niğde",
    "Ordu": "Ordu",             "Osmaniye": "Osmaniye",
    "Rize": "Rize",             "Sakarya": "Adapazarı",
    "Samsun": "Samsun",         "Sanliurfa": "Şanlıurfa",
    "Siirt": "Siirt",           "Sinop": "Sinop",
    "Sirnak": "Cizre",          "Sivas": "Sivas",
    "Tekirdag": "Tekirdağ",     "Tokat": "Tokat",
    "Trabzon": "Trabzon",       "Tunceli": "Tunceli",
    "Usak": "Uşak",             "Van": "Van",
    "Yalova": "Yalova",         "Yozgat": "Yozgat",
    "Zinguldak": "Zonguldak"
  },
  uae: {
    "Abu Dhabi": "Abu Dhabi",
    "Ajman": "Ajman",
    "Dubai": "Dubai",
    "Fujairah": "Fujairah",
    "Ras al-Khaimah": "Ras al-Khaimah",
    "Sharjah": "Sharjah",
    "Umm al-Quwain": "Umm al-Quwain"
  },
  egypt: {
    "Shamal Sina'":     "Arish",
    "Aswan":            "Aswan",
    "Al Bahr al Ahmar": "Hurghada",
    "Matruh":           "Marsa Matruh",
    "Al Wadi at Jadid": "Kharga",
    "As Suways":        "Suez",
    "Janub Sina'":      "At-Tur",
    "Bur Sa`id":        "Port Said",
    "Ad Daqahliyah":    "Mansoura",
    "Ash Sharqiyah":    "Zagazig",
    "Al Isma`iliyah":   "Ismailia",
    "Dumyat":           "Damietta",
    "Kafr ash Shaykh":  "Kafr el-Sheikh",
    "Al Buhayrah":      "Damanhur",
    "Al Iskandariyah":  "Alexandria",
    "Al Qahirah":       "Cairo",
    "Al Jizah":         "Giza",
    "Al Minya":         "Minya",
    "Al Fayyum":        "Faiyum",
    "Bani Suwayf":      "Beni Suef",
    "Al Minufiyah":     "Shibin el-Kom",
    "Al Qalyubiyah":    "Banha",
    "Al Gharbiyah":     "Tanta",
    "Suhaj":            "Sohag",
    "Qina":             "Qena",
    "Asyut":            "Asyut",
    "Luxor":            "Luxor"
  },
  southAfrica: {
    "Northern Cape":  "Kimberley",
    "KwaZulu-Natal":  "Pietermaritzburg",
    "Free State":     "Bloemfontein",
    "Eastern Cape":   "Bhisho",
    "Limpopo":        "Polokwane",
    "North West":     "Mahikeng",
    "Mpumalanga":     "Mbombela",
    "Western Cape":   "Cape Town",
    "Gauteng":        "Johannesburg"
  },
  thailand: {
    "Surin": "Surin",                             "Si Sa Ket": "Si Sa Ket",
    "Ubon Ratchathani": "Ubon Ratchathani",        "Sa Kaeo": "Aranyaprathet",
    "Buri Ram": "Buri Ram",                        "Trat": "Trat",
    "Chanthaburi": "Chanthaburi",                  "Satun": "Satun",
    "Songkhla": "Songkhla",                        "Yala": "Yala",
    "Narathiwat": "Narathiwat",                    "Chiang Rai": "Chiang Rai",
    "Chiang Mai": "Chiang Mai",                    "Mae Hong Son": "Mae Hong Son",
    "Tak": "Tak",                                  "Kanchanaburi": "Kanchanaburi",
    "Prachuap Khiri Khan": "Prachuap Khiri Khan",  "Phetchaburi": "Phetchaburi",
    "Ratchaburi": "Ratchaburi",                    "Chumphon": "Chumphon",
    "Ranong": "Ranong",                            "Phayao": "Phayao",
    "Nan": "Nan",                                  "Uttaradit": "Uttaradit",
    "Phitsanulok": "Phitsanulok",                  "Loei": "Loei",
    "Bueng Kan": "Bueng Kan",                      "Nong Khai": "Nong Khai",
    "Nakhon Phanom": "Nakhon Phanom",              "Mukdahan": "Mukdahan",
    "Amnat Charoen": "Amnat Charoen",              "Phangnga": "Phangnga",
    "Krabi": "Krabi",                              "Trang": "Trang",
    "Pattani": "Pattani",                          "Phatthalung": "Phatthalung",
    "Nakhon Si Thammarat": "Nakhon Si Thammarat",  "Surat Thani": "Surat Thani",
    "Samut Songkhram": "Samut Songkhram",           "Samut Sakhon": "Samut Sakhon",
    "Bangkok Metropolis": "Bangkok",               "Samut Prakan": "Samut Prakan",
    "Chachoengsao": "Chachoengsao",                "Phatthaya": "Pattaya",
    "Rayong": "Rayong",                            "Phuket": "Phuket",
    "Khon Kaen": "Khon Kaen",                      "Sakon Nakhon": "Sakon Nakhon",
    "Suphan Buri": "Suphan Buri",                  "Sing Buri": "Sing Buri",
    "Chai Nat": "Chai Nat",                        "Ang Thong": "Ang Thong",
    "Saraburi": "Saraburi",                        "Nakhon Ratchasima": "Nakhon Ratchasima",
    "Nakhon Nayok": "Nakhon Nayok",                "Pathum Thani": "Pathum Thani",
    "Uthai Thani": "Uthai Thani",                  "Kalasin": "Kalasin",
    "Roi Et": "Roi Et",                            "Maha Sarakham": "Maha Sarakham",
    "Nong Bua Lam Phu": "Nong Bua Lam Phu",        "Lop Buri": "Lop Buri",
    "Udon Thani": "Udon Thani",                    "Phra Nakhon Si Ayutthaya": "Phra Nakhon Si Ayutthaya",
    "Nonthaburi": "Nonthaburi",                    "Nakhon Pathom": "Nakhon Pathom",
    "Kamphaeng Phet": "Kamphaeng Phet",            "Lampang": "Lampang",
    "Sukhothai": "Sukhothai",                      "Nakhon Sawan": "Nakhon Sawan",
    "Phetchabun": "Phetchabun",                    "Phichit": "Phichit",
    "Chaiyaphum": "Chaiyaphum",                    "Phrae": "Phrae",
    "Lamphun": "Lamphun",                          "Prachin Buri": "Prachin Buri",
    "Yasothon": "Yasothon",                        "Chon Buri": "Chon Buri"
  },
  vietnam: {
    "Kon Tum": "Kon Tum",                          "Đắk Nông": "Gia Nghĩa",
    "Đắk Lắk": "Buôn Ma Thuột",                   "Gia Lai": "Pleiku",
    "Bình Phước": "Đồng Xoài",                     "Tây Ninh": "Tây Ninh",
    "Long An": "Tân An",                           "Ðong Tháp": "Cao Lãnh",
    "An Giang": "Long Xuyên",                      "Kiên Giang": "Rạch Giá",
    "Điện Biên": "Điện Biên Phủ",                  "Son La": "Sơn La",
    "Thanh Hóa": "Thanh Hóa",                      "Nghệ An": "Vinh",
    "Ha Tinh": "Hà Tĩnh",                          "Quảng Bình": "Đồng Hới",
    "Quảng Trị": "Đông Hà",                        "Thừa Thiên - Huế": "Huế",
    "Quàng Nam": "Tam Kỳ",                         "Hà Giang": "Hà Giang",
    "Cao Bằng": "Cao Bằng",                        "Lào Cai": "Lào Cai",
    "Lai Chau": "Lai Châu",                        "Lạng Sơn": "Lạng Sơn",
    "Quảng Ninh": "Hạ Long",                       "Sóc Trăng": "Sóc Trăng",
    "Tiền Giang": "Mỹ Tho",                        "Bà Rịa - Vũng Tàu": "Bà Rịa",
    "Hồ Chí Minh city": "Ho Chi Minh City",        "Khánh Hòa": "Nha Trang",
    "Cà Mau": "Cà Mau",                            "Bạc Liêu": "Bạc Liêu",
    "Hau Giang": "Vị Thanh",                       "Vĩnh Long": "Vĩnh Long",
    "Trà Vinh": "Trà Vinh",                        "Bến Tre": "Bến Tre",
    "Đông Nam Bộ": "Biên Hòa",                     "Bình Thuận": "Phan Thiết",
    "Ninh Thuận": "Phan Rang",                     "Phú Yên": "Tuy Hòa",
    "Bình Định": "Quy Nhơn",                       "Quảng Ngãi": "Quảng Ngãi",
    "Đà Nẵng": "Đà Nẵng",                         "Ninh Bình": "Ninh Bình",
    "Nam Định": "Nam Định",                        "Thái Bình": "Thái Bình",
    "Hải Phòng": "Hải Phòng",                      "Hòa Bình": "Hòa Bình",
    "Tuyên Quang": "Tuyên Quang",                  "Yên Bái": "Yên Bái",
    "Vĩnh Phúc": "Vĩnh Yên",                      "Phú Thọ": "Việt Trì",
    "Ha Noi": "Hanoi",                             "Đông Bắc": "Bắc Giang",
    "Đồng Bằng Sông Hồng": "Hải Dương",           "Bắc Ninh": "Bắc Ninh",
    "Bắc Giang": "Bắc Giang",                     "Thái Nguyên": "Thái Nguyên",
    "Hải Dương": "Hải Dương",                     "Hà Nam": "Phủ Lý",
    "Bình Dương": "Thủ Dầu Một",                  "Lâm Đồng": "Đà Lạt",
    "Can Tho": "Cần Thơ"
  },
  greece: {
    "Dytiki Makedonia":              "Kozani",
    "Ipeiros":                       "Ioannina",
    "Kentriki Makedonia":            "Thessaloniki",
    "Anatoliki Makedonia kai Thraki":"Komotini",
    "Ayion Oros":                    "Karyes",
    "Thessalia":                     "Larissa",
    "Stereá Elláda":                 "Lamia",
    "Attiki":                        "Athens",
    "Peloponnisos":                  "Tripoli",
    "Dytiki Ellada":                 "Patras",
    "Kriti":                         "Heraklion",
    "Notio Aigaio":                  "Ermoupoli",
    "Voreio Aigaio":                 "Mytilene",
    "Ionioi Nisoi":                  "Corfu"
  },
  europe: {
    "Germany": "Berlin",            "France": "Paris",
    "Italy": "Rome",                "Spain": "Madrid",
    "Portugal": "Lisbon",           "Netherlands": "Amsterdam",
    "Belgium": "Brussels",          "Luxembourg": "Luxembourg City",
    "Switzerland": "Bern",          "Austria": "Vienna",
    "Poland": "Warsaw",             "Czech Republic": "Prague",
    "Slovakia": "Bratislava",       "Hungary": "Budapest",
    "Romania": "Bucharest",         "Bulgaria": "Sofia",
    "Greece": "Athens",             "Croatia": "Zagreb",
    "Slovenia": "Ljubljana",        "Serbia": "Belgrade",
    "Bosnia and Herzegovina": "Sarajevo", "Montenegro": "Podgorica",
    "Albania": "Tirana",            "Macedonia": "Skopje",
    "Sweden": "Stockholm",          "Norway": "Oslo",
    "Finland": "Helsinki",          "Denmark": "Copenhagen",
    "Estonia": "Tallinn",           "Latvia": "Riga",
    "Lithuania": "Vilnius",         "Ireland": "Dublin",
    "United Kingdom": "London",     "Ukraine": "Kyiv",
    "Belarus": "Minsk",             "Moldova": "Chișinău",
    "Russia": "Moscow",             "Kazakhstan": "Astana",
    "Turkey": "Ankara",             "Cyprus": "Nicosia",
    "Malta": "Valletta",            "Iceland": "Reykjavik"
  },
  northAmerica: {
    "Canada": "Ottawa",
    "United States": "Washington D.C.",
    "Mexico": "Mexico City",
    "Guatemala": "Guatemala City",
    "Belize": "Belmopan",
    "El Salvador": "San Salvador",
    "Honduras": "Tegucigalpa",
    "Nicaragua": "Managua",
    "Costa Rica": "San José",
    "Panama": "Panama City",
    "Cuba": "Havana",
    "Jamaica": "Kingston",
    "Haiti": "Port-au-Prince",
    "Dominican Republic": "Santo Domingo",
    "Bahamas": "Nassau",
    "Barbados": "Bridgetown",
    "Trinidad and Tobago": "Port of Spain",
    "Saint Lucia": "Castries",
    "Grenada": "St. George's",
    "Antigua and Barbuda": "St. John's",
    "Dominica": "Roseau",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Vincent and the Grenadines": "Kingstown"
  },
  southAmerica: {
    "Argentina": "Buenos Aires",
    "Bolivia": "Sucre",
    "Brazil": "Brasília",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "Ecuador": "Quito",
    "Guyana": "Georgetown",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Suriname": "Paramaribo",
    "Uruguay": "Montevideo",
    "Venezuela": "Caracas"
  },
  africa: {
    "Algeria": "Algiers",
    "Angola": "Luanda",
    "Benin": "Porto-Novo",
    "Botswana": "Gaborone",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Cameroon": "Yaoundé",
    "Cape Verde": "Praia",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Comoros": "Moroni",
    "Democratic Republic of Congo": "Kinshasa",
    "Republic of Congo": "Brazzaville",
    "Djibouti": "Djibouti",
    "Egypt": "Cairo",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Swaziland": "Mbabane",
    "Ethiopia": "Addis Ababa",
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Ghana": "Accra",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Côte d'Ivoire": "Yamoussoukro",
    "Kenya": "Nairobi",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Mali": "Bamako",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Namibia": "Windhoek",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Rwanda": "Kigali",
    "Sao Tome and Principe": "São Tomé",
    "Senegal": "Dakar",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Somalia": "Mogadishu",
    "South Africa": "Pretoria",
    "South Sudan": "Juba",
    "Sudan": "Khartoum",
    "Tanzania": "Dodoma",
    "Togo": "Lomé",
    "Tunisia": "Tunis",
    "Uganda": "Kampala",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare"
  },
  asia: {
    "Afghanistan": "Kabul",
    "Armenia": "Yerevan",
    "Azerbaijan": "Baku",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Bhutan": "Thimphu",
    "Brunei": "Bandar Seri Begawan",
    "Cambodia": "Phnom Penh",
    "China": "Beijing",
    "Cyprus": "Nicosia",
    "Georgia": "Tbilisi",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Israel": "Jerusalem",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Lebanon": "Beirut",
    "Malaysia": "Kuala Lumpur",
    "Maldives": "Malé",
    "Mongolia": "Ulaanbaatar",
    "Myanmar": "Naypyidaw",
    "Nepal": "Kathmandu",
    "North Korea": "Pyongyang",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Palestine": "Ramallah",
    "Philippines": "Manila",
    "Qatar": "Doha",
    "Saudi Arabia": "Riyadh",
    "Singapore": "Singapore",
    "South Korea": "Seoul",
    "Sri Lanka": "Sri Jayawardenepura Kotte",
    "Syria": "Damascus",
    "Taiwan": "Taipei",
    "Tajikistan": "Dushanbe",
    "Thailand": "Bangkok",
    "Timor-Leste": "Dili",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "United Arab Emirates": "Abu Dhabi",
    "Uzbekistan": "Tashkent",
    "Vietnam": "Hanoi",
    "Yemen": "Sanaa"
  },
  oceania: {
    "Australia": "Canberra",
    "New Zealand": "Wellington",
    "Papua New Guinea": "Port Moresby",
    "Fiji": "Suva",
    "Solomon Islands": "Honiara",
    "Vanuatu": "Port Vila",
    "Samoa": "Apia",
    "Tonga": "Nukuʻalofa",
    "Kiribati": "South Tarawa",
    "Federated States of Micronesia": "Palikir",
    "Palau": "Ngerulmud",
    "Marshall Islands": "Majuro",
    "Nauru": "Yaren",
    "Tuvalu": "Funafuti"
  }
};

/* ============================================================
   MAP SUPPORT — which game types are available per map
   ============================================================ */
const MAP_SUPPORT = {
  india:        { name: true,  locate: true,  flag: false, capital: true  },
  usa:          { name: true,  locate: true,  flag: false, capital: true  },
  canada:       { name: true,  locate: true,  flag: false, capital: true  },
  australia:    { name: true,  locate: true,  flag: false, capital: true  },
  japan:        { name: true,  locate: true,  flag: false, capital: true  },
  germany:      { name: true,  locate: true,  flag: false, capital: true  },
  china:        { name: true,  locate: true,  flag: false, capital: true  },
  brazil:       { name: true,  locate: true,  flag: false, capital: true  },
  spain:        { name: true,  locate: true,  flag: false, capital: true  },
  uae:          { name: true,  locate: true,  flag: false, capital: true  },
  argentina:    { name: true,  locate: true,  flag: false, capital: true  },
  france:       { name: true,  locate: true,  flag: false, capital: true  },
  indonesia:    { name: true,  locate: true,  flag: false, capital: true  },
  italy:        { name: true,  locate: true,  flag: false, capital: true  },
  mexico:       { name: true,  locate: true,  flag: false, capital: true  },
  nigeria:      { name: true,  locate: true,  flag: false, capital: true  },
  pakistan:     { name: true,  locate: true,  flag: false, capital: true  },
  russia:       { name: true,  locate: true,  flag: false, capital: true  },
  southKorea:     { name: true,  locate: true,  flag: false, capital: true  },
  turkey:         { name: true,  locate: true,  flag: false, capital: true  },
  egypt:          { name: true,  locate: true,  flag: false, capital: true  },
  southAfrica:    { name: true,  locate: true,  flag: false, capital: true  },
  thailand:       { name: true,  locate: true,  flag: false, capital: true  },
  vietnam:        { name: true,  locate: true,  flag: false, capital: true  },
  greece:         { name: true,  locate: true,  flag: false, capital: true  },
  europe:       { name: true,  locate: true,  flag: true,  capital: true  },
  northAmerica: { name: true,  locate: true,  flag: true,  capital: true  },
  southAmerica: { name: true,  locate: true,  flag: true,  capital: true  },
  africa:       { name: true,  locate: true,  flag: true,  capital: true  },
  asia:         { name: true,  locate: true,  flag: true,  capital: true  },
  oceania:      { name: true,  locate: true,  flag: true,  capital: true  },
  world:        { name: true,  locate: true,  flag: true,  capital: true  },
};

/* ============================================================
   INDIA UNION TERRITORIES — Easter Egg Bonus
   ============================================================ */
const INDIA_UTS = [
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

/* ============================================================
   MAP ACCENT COLORS — per-continent theming
   ============================================================ */
const MAP_COLORS = {
  africa:       { accent: "#F59E0B", glow: "rgba(245,158,11,0.28)"  },
  asia:         { accent: "#14B8A6", glow: "rgba(20,184,166,0.28)"  },
  europe:       { accent: "#3B82F6", glow: "rgba(59,130,246,0.28)"  },
  northAmerica: { accent: "#22C55E", glow: "rgba(34,197,94,0.28)"   },
  southAmerica: { accent: "#10B981", glow: "rgba(16,185,129,0.28)"  },
  oceania:      { accent: "#8B5CF6", glow: "rgba(139,92,246,0.28)"  },
  world:        { accent: "#E8604A", glow: "rgba(232,96,74,0.28)"   },
};